import { useState, type FormEvent } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import { User, BookOpen, Clock3, Flame, CalendarDays, Mail, CheckCircle2 } from 'lucide-react';

const Profile = () => {
  const [name, setName] = useState(() => localStorage.getItem('profileName') ?? 'Andi Student');
  const [email, setEmail] = useState(() => localStorage.getItem('profileEmail') ?? 'andi@example.com');
  const [isSaved, setIsSaved] = useState(false);
  const saveProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); localStorage.setItem('profileName', name.trim()); localStorage.setItem('profileEmail', email.trim()); setIsSaved(true); };

  return <DashboardLayout><div className="max-w-5xl mx-auto md:mx-0 pb-16">
    <div className="mb-12"><h1 className="text-5xl font-['Kalam',cursive] font-bold text-gray-900 dark:text-gray-100 mb-2 flex items-center gap-4"><User className="w-10 h-10" /> My Profile</h1><p className="text-gray-600 dark:text-gray-400 font-bold text-lg">View your learning progress and account information.</p></div>
    <div className="space-y-10">
      <section className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-md p-6 md:p-8 rounded-3xl border-2 border-gray-200 dark:border-gray-700 shadow-[6px_6px_0px_0px_rgba(156,163,175,0.35)]"><div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-7"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-2xl bg-blue-500 text-white flex items-center justify-center font-['Kalam',cursive] text-3xl font-bold">{name.trim().charAt(0).toUpperCase() || 'A'}</div><div><h2 className="text-3xl font-['Kalam',cursive] font-bold text-gray-900 dark:text-gray-100">{name || 'Andi Student'}</h2><p className="text-gray-600 dark:text-gray-400 font-semibold flex items-center gap-2"><Mail className="w-4 h-4" /> {email || 'andi@example.com'}</p></div></div><div className="bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 px-4 py-2 rounded-xl font-bold flex items-center gap-2 w-fit"><CheckCircle2 className="w-5 h-5" /> Active learner</div></div>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{label:'Courses joined',value:'4',icon:BookOpen,color:'text-blue-600 bg-blue-100 dark:bg-blue-900/40'},{label:'Lessons completed',value:'18',icon:CheckCircle2,color:'text-green-600 bg-green-100 dark:bg-green-900/40'},{label:'Hours learned',value:'12.5',icon:Clock3,color:'text-purple-600 bg-purple-100 dark:bg-purple-900/40'},{label:'Current streak',value:'3 days',icon:Flame,color:'text-orange-600 bg-orange-100 dark:bg-orange-900/40'}].map(({label,value,icon:Icon,color})=><div key={label} className="bg-gray-50 dark:bg-gray-900/50 p-4 rounded-2xl border border-gray-200 dark:border-gray-700"><div className={`w-9 h-9 rounded-xl flex items-center justify-center mb-3 ${color}`}><Icon className="w-5 h-5" /></div><p className="text-2xl font-bold text-gray-900 dark:text-gray-100">{value}</p><p className="text-sm font-semibold text-gray-500 dark:text-gray-400">{label}</p></div>)}</div></section>
      <section className="bg-yellow-100 dark:bg-yellow-900/40 p-8 rounded-3xl border-4 border-yellow-300 dark:border-yellow-700/50 shadow-[8px_8px_0px_0px_rgba(250,204,21,1)] dark:shadow-[8px_8px_0px_0px_rgba(161,98,7,0.8)] transform rotate-1 relative"><h2 className="text-3xl font-['Kalam',cursive] font-bold text-yellow-900 dark:text-yellow-300 mb-6 flex items-center gap-3"><User className="w-8 h-8" /> Account Profile</h2><div className="grid lg:grid-cols-[1fr_0.7fr] gap-8 items-start"><form className="space-y-6" onSubmit={saveProfile}><div><label className="block text-yellow-900 dark:text-yellow-100 font-bold mb-2 text-sm uppercase">Full Name</label><input type="text" value={name} onChange={(event)=>{setName(event.target.value);setIsSaved(false)}} required className="w-full px-4 py-3 rounded-xl border-2 border-yellow-200 bg-white/90 dark:bg-gray-800/90 text-gray-800 dark:text-gray-100 font-bold" /></div><div><label className="block text-yellow-900 dark:text-yellow-100 font-bold mb-2 text-sm uppercase">Email Address</label><input type="email" value={email} onChange={(event)=>{setEmail(event.target.value);setIsSaved(false)}} required className="w-full px-4 py-3 rounded-xl border-2 border-yellow-200 bg-white/90 dark:bg-gray-800/90 text-gray-800 dark:text-gray-100 font-bold" /></div><button type="submit" className="bg-yellow-400 hover:bg-yellow-500 text-yellow-900 font-bold py-3 px-8 rounded-xl font-['Kalam',cursive] text-xl border-2 border-yellow-500">Save Profile</button>{isSaved && <p className="text-sm font-bold text-green-700 dark:text-green-300">Profile saved on this device.</p>}</form><aside className="bg-white/55 dark:bg-gray-800/50 rounded-2xl border-2 border-yellow-200 dark:border-yellow-800/50 p-5"><h3 className="font-['Kalam',cursive] text-2xl font-bold text-yellow-900 dark:text-yellow-200 mb-4">Account information</h3><dl className="space-y-4 text-sm"><div className="flex gap-3"><User className="w-5 h-5 text-yellow-700 shrink-0" /><div><dt className="font-bold text-yellow-900 dark:text-yellow-100">Account type</dt><dd className="text-yellow-800 dark:text-yellow-300">Free learner</dd></div></div><div className="flex gap-3"><CalendarDays className="w-5 h-5 text-yellow-700 shrink-0" /><div><dt className="font-bold text-yellow-900 dark:text-yellow-100">Registered</dt><dd className="text-yellow-800 dark:text-yellow-300">18 July 2026</dd></div></div><div className="flex gap-3"><Mail className="w-5 h-5 text-yellow-700 shrink-0" /><div><dt className="font-bold text-yellow-900 dark:text-yellow-100">Login email</dt><dd className="text-yellow-800 dark:text-yellow-300 break-all">{email || 'andi@example.com'}</dd></div></div></dl></aside></div></section>
    </div>
  </div></DashboardLayout>;
};
export default Profile;
